name: Barbara Parker Creative Studio
favicon: null
layout_spectrum: 0.6621572833973914
typography_spectrum: 0.7500104298815131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9346252402756363
  lightness: 0.4489047466777265
  saturation: 0.9795222249813378
  rhythmicContrast: 0.6647195292171091
purpose: []
